### ISSUE TITLE
The date format is not working

### ISSUE THREAD

**Issue by felipesp88** [freshbitsweb/laratables#10]
When I tried  to show the `createad_at` column, it appeared like this `[object Object]`.

I configured the format that I want, but it didn't appear.

**Comment by gauravmak** [comment]
@felipesp88 Is the column the instance of `Carbon`?

By default, `created_at` and `updates_at` are carbon instances. You spelled it wrong in the issue description I guess.

**Comment by felipesp88** [comment]
It is Carbon and I spelled it wrong.

If I change, in the class `RecordsTransformer`, the test to `instanceof \Carbon\Carbon`, it works perfectly.

**Comment by gauravmak** [comment]
Should be fixed with the new release, thanks.
