### ISSUE TITLE
Error Order Relational Column

### ISSUE THREAD

**Issue by fadhil1106** [freshbitsweb/laratables#107]
I get error when I tried to sort category column.

DataTables warning: table id=list-item - The 'category.category' column is not in the select column list. Please add it to the select columns or make it - orderable : false

            let itemTable = $('#list-item').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{{ route('master-data.item.getdata') }}",
                columns: [
                    { name: 'id', visible: false},
                    { name: 'no', orderable: false, searchable: false },
                    { name: 'item_name', orderable: true, searchable: true},
                    { name: 'unit', orderable: true, searchable: true },
                    { name: 'category.category', orderable: true, searchable: true },
                    { name: 'stock.qty', orderable: true, searchable: true },
                    { name: 'action', orderable: false, searchable: false },
                ],
            });

**Comment by gauravmak** [comment]
That's expected. We cannot sort records by a relationship column directly. Please check [this section](https://github.com/freshbitsweb/laratables#ordering-sorting) in the readme.

![image](https://user-images.githubusercontent.com/11887260/157584949-6f4f21a8-598b-43a1-9634-8bd0ac18b44c.png)
