### ISSUE TITLE
Passe Custom Data Seach

### ISSUE THREAD

**Issue by dev-guidolin** [freshbitsweb/laratables#108]
Hi, how can i handle with custom data search on client and server side, when i try pass data to de server side to "laratablesSearchType()", the filter do not applyed.

is possible to use de "where","whereBetween"... to filter date?

var table = $('#teste').DataTable({
                serverSide: true,
                searching: false,
                destroy: true,
                language: {
                    "url": "//cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json"
                },
                ajax: {
                    url: "{{ route('representative.commission.index') }}",
                    data: function (d) {
                        d.search = {value: data, regex: false};
                    }
                },
                columns: [
                    {name: 'product_id'},
                    {name: 'client.name'},
                    {name: 'salesman.name'},
                    {name: 'amount'},
                    {name: 'status'},
                    //{ name: 'actions' },
                ],
            });`
`

**Comment by gauravmak** [comment]
Searching works out of the box if the table column name matches the table column name. If the table column name is different, you can add a custom method in your model as per the [docs](https://github.com/freshbitsweb/laratables#searching).

**Comment by dev-guidolin** [comment]
Ok, dit pass de data from datablem frontend to the laratablesSearch function, but, o can't use $query->whereBetween, jut $query->orWhere.

How can i use the $searchValue in other funcion? or how can i use other modelmethods inside the laratablesSearch?

**Comment by dev-guidolin** [comment]
`public static function laratablesQueryConditions($query,$searchValue)
    {
        $string= explode("-",$searchValue);
        $data = explode('_',$string[1]);
        $start= $data[0];
        $end= $data[1];

        return $query->whereBetween('created_at', [$start,$end]);
    }


    public static function laratablesSearchType($query, $searchValue)
    {
       return self::laratablesQueryConditions($query,$searchValue);
    }`

**Comment by gauravmak** [comment]
`laratablesQueryConditions()` method is called every time. I guess you want something only when the user searches in the table.

Please re-read the readme file. And if you still can't figure it out, share front as well as back end side code. I may be able to help.

**Comment by dev-guidolin** [comment]
Thanks a lot for your time, my problem is using the search value in laratablesSearch function.
I need to fetch data between two dates
![code](https://user-images.githubusercontent.com/53698169/165745780-4e85c600-2c1e-495a-b571-4f7677cb344a.png)

**Comment by gauravmak** [comment]
Okay, and what is the error you are facing?

**Comment by dev-guidolin** [comment]
When a try whereBetween, retur empty.
![code2](https://user-images.githubusercontent.com/53698169/165748456-f616c135-4960-442a-a649-420c511ec237.png)

if i change de collumn name, return empty too.
![code3](https://user-images.githubusercontent.com/53698169/165748765-88085ffd-4600-4bd6-bd31-05f21b154b4c.png)

**Comment by gauravmak** [comment]
try `laratablesSearchCreatedAt`

**Comment by dev-guidolin** [comment]
I did, return emmpty
Is possible use whereBetween in any case?

![code4](https://user-images.githubusercontent.com/53698169/165753087-18c7c2ea-68d3-4edd-8203-9021b6e774ec.png)
![code5](https://user-images.githubusercontent.com/53698169/165753607-7c507937-415c-4044-a4be-968e786e735b.png)

**Comment by gauravmak** [comment]
Try `orWhereBetween`

**Comment by dev-guidolin** [comment]
Nice! now it is working! Greate, many thanks :)

**Comment by dev-guidolin** [comment]
just one more question, when it is necessary to use more than one clause? no search function()
![code6](https://user-images.githubusercontent.com/53698169/165759566-c8072643-e608-407b-8728-e24561d2b205.png)

**Comment by gauravmak** [comment]
Didn't get the question. What is the goal?

**Comment by dev-guidolin** [comment]
I need filter by range date and status in the same time

**Comment by gauravmak** [comment]
You can add another method `laratablesSearchStatus`

**Comment by dev-guidolin** [comment]
Yes, I had done that, but it will continue to compose the query with orWhere. what I need:
`where('status',$dinamicStatus)->whereBetween('created_at',[$start,$end])`

**Comment by dev-guidolin** [comment]
[gauravmak](https://github.com/gauravmak), i do it! so, i don't know how, i guess, i clear cache and now it is working. Thankyou
