### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by GPATEL419** [freshbitsweb/laratables#112]
When are you planning to make Laravel 11 updates @gauravmak

**Comment by gauravmak** [comment]
Hi,

There is an [automated PR from the Laravel shift](https://github.com/freshbitsweb/laratables/pull/111). Can you please help test that on your Laravel 11 app and see if everything works well?

Thanks.

**Comment by gauravmak** [comment]
You may post your findings on the [PR page](https://github.com/freshbitsweb/laratables/pull/111) directly.
