### ISSUE TITLE
ErrorException (E_NOTICE) Undefined index

### ISSUE THREAD

**Issue by Webmobsoft** [freshbitsweb/laratables#12]
i get undefined index error when i try to use getlaraData function 
my controller file
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Product;
use Freshbitsweb\Laratables\Laratables;

class DataTableController extends Controller
{
    public function index(){
        return view('admin.chef');
    }

    public function getlaraData()
    {
        return Laratables::recordsOf(User::class);
    }
}

and this is my script code in view folder

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#simple-datatable-example').DataTable({
                serverSide: true,
                processing: true,
                responsive: true,
                ajax: "{{ route('admin.getlaraData') }}",
                columns: [
                    { name: 'username' },
                    { name: 'email' },
                    { name: 'password' },
                    { name: 'first_name' },
                    { name: 'last_name' },
                    { name: 'country' }
                ],
            });
        });
    </script>
@endsection

**Comment by bonucci** [comment]
What was the issue?
