### ISSUE TITLE
Add dpownload functionality

### ISSUE THREAD

**Issue by alfredlaggner** [freshbitsweb/laratables#14]
I am working on implementing laratables for downloading images. One of the database fields contains the file name.

Without laratables installed  I can download like this
In my controller:
`public function download($id)
{
   $coa = Coa::find($id);
   return Storage::download('coapath/' . $coa->coa_name);
}`

How can I do this with laratables? I already added an extra column with a download button. But I am not able to trigger the download.

You can test it in coa.ozinc.work

I also created a seperate jQuery ajax function but it returns error 
`
﻿
coas.ozinc.work/publ…/uploads/OZ14.pdf:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
(index):137 GET http://coas.ozinc.work/public/uploads/BOC_FG_LEMFUEL_180820.sql net::ERR_NAME_NOT_RESOLVED`
Here is my script:
` <script>
            $(document).ready(function () {
                $('#coa_table').DataTable({
                    serverSide: true,
                    processing: true,
                    responsive: true,
                    ajax: "{{ route('get_extra_data_datatables_attributes_data') }}",
                    columns: [
                        {name: 'id'},
                        {name: 'product_name'},
                        {name: 'coa_number'},
                        {name: 'coa_name'},
                        {name: 'action', orderable: false, searchable: false}

                    ],
                });

                /*

                                $('#extra-data-datatables-attributes').on('click', 'tr', function () {
                                    alert('Clicked row id is: ' + $(this).data('coa_name'));
                                }
                */

                $.ajaxTransport("+binary", function (options, originalOptions, jqXHR) {
                    // check for conditions and support for blob / arraybuffer response type
                    if (window.FormData && ((options.dataType && (options.dataType == 'binary')) || (options.data && ((window.ArrayBuffer && options.data instanceof ArrayBuffer) || (window.Blob && options.data instanceof Blob))))) {
                        return {
                            // create new XMLHttpRequest
                            send: function (_, callback) {
                                // setup all variables
                                var xhr = new XMLHttpRequest(),
                                    url = options.url,
                                    type = options.type,
                                    // blob or arraybuffer. Default is blob
                                    dataType = options.responseType || "blob",
                                    data = options.data || null;

                                xhr.addEventListener('load', function () {
                                    var data = {};
                                    data[options.dataType] = xhr.response;
                                    // make callback and send data
                                    callback(xhr.status, xhr.statusText, data, xhr.getAllResponseHeaders());
                                });

                                xhr.open(type, url, true);
                                xhr.responseType = dataType;
                                xhr.send(data);
                            },
                            abort: function () {
                                jqXHR.abort();
                            }
                        };
                    }
                });
                $('#coa_table').on('click', 'tr', function () {

                    var url = $(this).data('coa_path');
                    $.ajax({
                        url: url,
                        type: "GET",
                        dataType: 'binary',
                        success: function (result) {
                            var url = URL.createObjectURL(result);
                            var $a = $('<a />', {
                                'href': url,
                                'download': 'document.txt',
                                'text': "click"
                            }).hide().appendTo("body")[0].click();
                            setTimeout(function () {
                                URL.revokeObjectURL(url);
                            }, 10000);
                        }
                    });
                })
`

**Comment by gauravmak** [comment]
I think you are mixing 2 things here. Downloading a file is a separate task and Laratables needs to just return the file name which is already in the column `coaname`.

If you want to return a download button instead of just the file name, you can use the (Customize the column value)[https://github.com/freshbitsweb/laratables#customizing-column-values] and return button HTML instead. Something like this: 

```php
/**
 * Returns truncated name for the datatables.
 *
 * @return string
 */
public function laratablesCoaName()
{
    return view('buttom_html', ['coa_name' => $this->coa_name])->render();
}
```

And `buttom_html` blade view file can contain buttom HTML.
