### ISSUE TITLE
extra filters

### ISSUE THREAD

**Issue by coding-sunshine** [freshbitsweb/laratables#16]
I want to pass some condition to the back-end and based on that condition I want to modify the query condition
for example
```
    public static function laratablesQueryConditions($query)
    {
        if($withTrashed == true){
           return $query->withTrashed();
        }
    }
```
How can I achieve this? as I need to find a way to pass another variable(maybe through $request or any other mean) but   laratablesQueryConditions just takes one param
Please help

**Comment by gauravmak** [comment]
Currently, I am doing it via sessions in a couple of the projects.

When use specifies filters outside datatables, I would set the value in session and add a condition in the `laratablesQueryConditions` method using the session value.

**Comment by coding-sunshine** [comment]
not the solution I would love to do, kind of hacky, as it moves away from the base package. But I will also think of some solution.

**Comment by gauravmak** [comment]
Another solution would be to send the filter's data [from datatables](https://datatables.net/examples/server_side/custom_vars.html) and using them on Laravel side via `request()` helper.

**Comment by coding-sunshine** [comment]
actually this solution worked for me https://github.com/freshbitsweb/laratables/pull/11

**Comment by gauravmak** [comment]
That pull request is merged now @coding-sunshine Thanks.

**Comment by coding-sunshine** [comment]
thanks very much @gauravmak
