### ISSUE TITLE
Exist some attribute name hide, hidden or disabled?

### ISSUE THREAD

**Issue by GersonRosales** [freshbitsweb/laratables#18]
I want hide some columns by example
```
columns: 
[
     { name: 'id'},
     { name: 'company', orderable: true},
     { name: 'code', hide: true},
],```
exist some attribute name hide, hidden or disabled

**Comment by gauravmak** [comment]
Laratables' job is to just fetch the values of the columns that you wish from the database and present them to Datatables.

Only datatables itself can help you with [hidden columns](https://datatables.net/examples/basic_init/hidden_columns.html).
