### ISSUE TITLE
relation failing

### ISSUE THREAD

**Issue by jim1506** [freshbitsweb/laratables#19]
I have a table of advertisers and one of regions. The advertiser has a field region_id and is defined as a belongs to relationship. Laratables is not picking up the relationship. The regions table has a field region which is what I wish to show.

The relationship is defined as

`public function getRegion()
   {
       return $this->hasOne('App\Regions','id','region_id');
   }`

Although not necessary I put in the fields in trying to get the datatable to work.

so my table has the following javascript call (I have added buttons etc):

`<script>
    $(document).ready(function() {
          $('#thetable').DataTable( {
              dom: 'lBfrtip',
                  "iDisplayLength": 25,
                  "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ],
                  serverSide: true,
                  processing: true,
                  responsive: true,
                  ajax: "{{ route('advertisersLaratables') }}",
                  columns: [
                    { name: 'firstname' },
                    { name: 'surname' },
                    { name: 'companyName' },
                    { name: 'email' },
                    { name: 'town' },
                    { name: 'getRegion.region'}
                ],

                  columnDefs: [
                     {'orderable':false, "targets":[3,4]    }
                   ],
                  buttons: [
                     { extend:'copy',
                           text: '<span style="color:darkblue" title="copy"><i class="fa fa-clone"></i></span>',
                      },
                      {extend: 'print',
                          title: 'Advertisers - <?php echo $today_f; ?>',
                          text: '<span style="color:darkblue" title="print"><i class="fa fa-print"></i></span>',
                      },
                      {extend: 'excel',
                          filename: 'Advertisers - <?php echo $today_f; ?>',
                         text: '<span style="color:darkblue" title="Excel"><i class="fa fa-file-excel"></i></span>',
                          footer:true,
                      },
                      {extend: 'pdf',
                          filename:  'Advertisers - <?php echo $today_f; ?>',
                          text: '<span style="color:darkblue" title="pdf"><i class="fa fa-file-pdf"></i></span>',
                      },
                      {extend:'csvHtml5',
                          filename: 'Advertisers - <?php echo $today_f; ?>',
                          text: '<span style="color:darkblue" title="csv"><i class="fab fa-html5" aria-hidden="true"></i></span>',
                      },
                      {extend: 'collection',
                          text:'<span style="color:darkblue" title="show/hide columns "><i class="fa fa-columns"></i></span>',
                          buttons:['columnsVisibility'] }
                      ]
          } );
      } );

    </script>`

Although I have checked this with tinker etc I just get N/A for the region name.

**Comment by gauravmak** [comment]
Is it a `hasOne` relationship or a `belongsTo` relationship?

Does it work when you fetch a region of the advertiser directly? For example,

```php
$advertisers = Advertiser::with('getRegion')->all();

foreach ($advertisers as $advertiser) {
    dump($advertiser->getRegion->region);
}
```

**Comment by jim1506** [comment]
The relationship is:
`
public function getRegion()
   {
       return $this->hasOne('App\Regions','id','region_id');
   }

I have just run the following:

`$advertisers = Advertiser::with('getRegion')->limit(10)->get();
dd($advertisers;`

and the relationship worked fine


`

**Comment by agrandin** [comment]
I have got the same issue, but my relationship is showing like 1 for each 20 or 30th item. So sometimes it works fine othertimes not.

**Comment by gauravmak** [comment]
Will look into it.

**Comment by gauravmak** [comment]
I just checked and HasOne relationship is also working fine. Can you reproduce in other schema?

Though, we don't have a sample HasOne relationship code in the example repo.
Here's how I just checked it quickly.

1) Cloning this repo - https://github.com/freshbitsweb/laravel-relationships-data
2) Installing it and laratables package
3) Replacing the code in `welcome.blade.php` and `routes/web.php` with this - https://pastebin.com/hgS9DitX

**Comment by msl2000** [comment]
Problem appeared for me as well. Trying to get a hasone relationship and checked that the relationship worked fine. The relationship is: 

```
class Sponsor extends Model
{
    protected $table = 'sponsors';
    protected $with = ['image'];
....

public function image(){
        return $this->hasOne(Image::class, 'id', 'image_id');
    }
```

In the dataTable trying to pull the data as:

```
                 {
                    name: 'image.source', render: function (data, type, row) {
                    return '<img src="' + data + '" class="circle circle-xs">';
                    },
                    orderable: false
                },

```

Error I receive:

error: "The 'image.source' column is not in the select column list. Please add it to the select columns or make it - orderable : false"

**Comment by gauravmak** [comment]
Please refer to #32 .
