### ISSUE TITLE
change search able column 

### ISSUE THREAD

**Issue by mirabdolbaghi2** [freshbitsweb/laratables#21]
hi 
i'm using persian language to search but i get this error:
SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' (SQL: select count(*) as aggregate from `posts` where (`id` like %س% or `title` like %س% or `created_at` like %س%))

it because of search in created_at column 
how can i change the searchable column or search query ???
 i know i cant use {searchable:false} but it is laratables Additional Columns and i cant disable search for it

**Comment by gauravmak** [comment]
Right. I think we should keep them non-searchable by default. And developer can add another method to specify additional searchable columns.

**Comment by gauravmak** [comment]
Fixed in latest release. Thanks.
