### ISSUE TITLE
Relationship Sorting

### ISSUE THREAD

**Issue by jfvoliveira** [freshbitsweb/laratables#25]
I am having trouble sorting the table by a relationship column.
Imagine a products table with the columns: id, name, store.name.
If I set store.name to be sortable, I get an error.

How can I make the Store Name sortable? I have this function but with no avail:

```
public static function laratablesOrderStoreName()
{
    return 'store.Name';
}
```

What am I doing wrong?

Thanks

**Comment by gauravmak** [comment]
As the readme suggests - 
![screenshot from 2018-10-28 13-00-32](https://user-images.githubusercontent.com/11887260/47613246-8332a100-dab1-11e8-8528-49bcb945aad7.png)

Eloquent makes another query for fetching data from the relationship table. Therefore, orderby cannot work for the relationship column.

**Comment by jfvoliveira** [comment]
The way I interpret that text in both cases (relations or custom) we could turn it off or create the static method. 

In any case, I can create a custom field that is the relationship result and then sort that field, right?

**Comment by gauravmak** [comment]
Sorting needs to be done on the DB side.

If the total number of records that you wish to display are not more than a few hundred, you can skip the server side part altogether and fetch all records from the beginning.

**Comment by malfianrasyidin** [comment]
Do you mind to give more sample codes to do these relationship sorting? Thanks!

**Comment by gauravmak** [comment]
As I said, ordering cannot work with relationships as Eloquent makes a separate query for fetching relationship data.
