### ISSUE TITLE
Adding ordering doubles rendering time 

### ISSUE THREAD

**Issue by ditsbroefs** [freshbitsweb/laratables#27]
When adding ordering on client JavaScript 

```
var table = $('#clients-table').DataTable({
    serverSide: true,
    ajax:       '{!! action('ClientsController@managed_clientsfordatatable', ['partner_approved' => $partner_approved]) !!}',
    columns: [
        { name: 'checkforapprove', searchable: false, orderable: false },
        { name: 'id', searchable: true,  orderable: true  },
        ...
        { name: 'actions', searchable: false, orderable: false },
    ],
    'order': [[12, 'desc']]
});
```

render time doubles. I can set the ordering server side as well, but then how do I indicate current  ordering column and direction?

P.S. Absolutely wonderful package! Works extremely easy and smooth and is still very powerful!!

**Comment by gauravmak** [comment]
Thanks.

Do you mean Datatables render time? I fear we can't anything in that case.
You're right that ordering should not be set on server side directly unless you keep all the columns non-orderable.

Am curious - How did you test the render time? What were the numbers?

**Comment by ditsbroefs** [comment]
I'm measuring the time the ajax request takes in Chrome. There are something like 225000 records of the model I'm querying. I'm doing some eager loading. Without the order clause the request takes between 100 and 135 ms. When I add the client side order it takes between 220 and 280 ms. It's still very acceptable, but it would be nice it could be halved!

**Comment by gauravmak** [comment]
Ordering would just tell Query builder to order the records.
I am not sure if we can do anything here.

**Comment by ditsbroefs** [comment]
Understand. Thanks. And thanks again for excellent package!
