### ISSUE TITLE
Get another column data using row[columnName] instead of row[columnIndex], is it possible?

### ISSUE THREAD

**Issue by ervansanjaya** [freshbitsweb/laratables#28]
Good day everyone,

In client-side I used 'data' to supply the column value, in Laratables as far as I know we need to use 'name' to select column from database, and returned as index [0, 1, n]

I can access other column via render using row[columnIndex], but how can I achieve it by row[columnName]?

Sample code:
```
{ title: 'Status', name: 'status', className: 'text-center', visible: false },
{ 
  title: 'Action', name: 'id', render: function(data, type, row) {
    // I want to access 'status' column from here
    if (row['status'] == 'T') return '1';
    else return '2';
  }
}
```

Thank you for your attention and support.
Thank you for making this great library! <3

**Comment by ervansanjaya** [comment]
I solved this by using laratablesCustomColumn(), pardon me.

**Comment by RyanNutt** [comment]
@ervansanjaya Do you mind sharing how you did this? I'm wanting to do the same thing.

**Comment by ervansanjaya** [comment]
@RyanNutt Hi Ryan,
I ended up using laratablesCustomColumn($model) to create a 'custom' callable column that later can be 'called' in datatable's column definition (https://github.com/freshbitsweb/laratables#custom-columns), say I want to create **action**. 

I created a public static function
```
public static function laratablesCustomAction($user) {
   // Here I return a view
  return view('custom')->with('user', $user)->render();
}
```

```
- custom.blade.php

{{ $user->name }}
<button user_id={{ $user->id }}>Edit ID</button>
```

Later in datatable
```
 columns: {
   ....
   { 
      title: 'Action', 
      name: 'action', 
      className: 'text-center not-selectable', 
      orderable: false, 
      searchable: false 
   },
   ....
 }
```
That's it. But another trouble comes in when I need to select another column from database that I didn't select in the datatable's column, say it's user's **email**. Then I have to create laratablesAdditionalColumns() method inside my user model to select the column that doesnt get selected in datatable's column definition (https://github.com/freshbitsweb/laratables#selecting-additional-columns)

```
public static function laratablesAdditionalColumns()
    {
        return 
        [
            'email', 
            // add another
        ];
    }

```

Have a try. Hopefully it helps.
