### ISSUE TITLE
Individual column searching

### ISSUE THREAD

**Issue by chongzia** [freshbitsweb/laratables#29]
Edit in the table. Can you update it here?
This should be a very common function.
However, there may be more types of forms to consider
If the author is willing to update

in addition
If I use more search status, how should datatable plug-ins be associated ?

**Comment by gauravmak** [comment]
Are you referring to [Datatables Editor](https://editor.datatables.net/)?

I didn't get your other question about plugins.

**Comment by chongzia** [comment]
I'm following the guidelines given on the DataTable website.
http://www.datatables.club/example/api/multi_filter.html

I'm following this rule and add some functionality to your PHP code
The first addition is the search for each paragraph.

Sorry, my English is not very good.

```
$(document).ready(function()
{
	var table = $('#admin-table').DataTable(
	{
		"bProcessing" : true, //DataTables载入数据时，是否显示‘进度’提示
		"serverSide": true,
		 "oLanguage":
		 { //国际化配置
			"sProcessing" : "正在获取数据，请稍后...",  
			"sLengthMenu" : "显示 _MENU_ 条",  
			"sZeroRecords" : "没有您要搜索的内容",  
			"sInfo" : "从 _START_ 到  _END_ 条记录 总显示记录数为 _TOTAL_ 条",  
			"sInfoEmpty" : "记录数为0",  
			"sInfoFiltered" : "(共显示 _MAX_ 条数据)",  
			"sInfoPostFix" : "",  
			"oPaginate":
			{  
				"sFirst" : "第一页",  
				"sPrevious" : "上一页",  
				"sNext" : "下一页",  
				"sLast" : "最后一页"  
			}
		},
		"ajax":"{{action('Admin\\AdminController@list') }}",
		// 数据展示
		"columns":
		[
			{ name: 'id' },
			{ name: 'username' },
			{ name: 'name' },
			{ name: 'email' },
			{ name: 'phone' },
			{ name: 'status' },
			{ name: 'created_at' },
		],
	});

	$('#admin-table tfoot th').each( function ()
	{
		var title = $('#admin-table thead th').eq( $(this).index() ).text();
		if (title == '用户名')
		{
			$(this).html( '<input type="text" name="username" placeholder="搜索 '+title+'" style="width:100%"/>' );
		}
		if (title == '姓名')
		{
			$(this).html( '<input type="text" name="name" placeholder="搜索 '+title+'" style="width:100%"/>' );
		}
		if (title == '邮件')
		{
			$(this).html( '<input type="text" name="email" placeholder="搜索 '+title+'" style="width:100%"/>' );
		}
		if (title == '电话')
		{
			$(this).html( '<input type="text" name="phone" placeholder="搜索 '+title+'" style="width:100%"/>' );
		}
		if (title == '状态')
		{
			$(this).html( '<select><option name="status" value="0">请选择状态</option><option value="1">正常</option><option value="2">禁止</option></select>' );
		}
		if (title == '注册日期')
		{
			$(this).html( '<input type="date" name="created_at" placeholder="搜索 '+title+'" value="{{date("Y-m-d",time())}}" style="width:100%"/>' );
		}
	});
	table.columns().eq( 0 ).each( function ( colIdx )
	{
		$( 'input', table.column( colIdx ).footer() ).on( 'keyup change', function ()
		{
			table.column( colIdx ).search( this.value ).draw();
		});
	});
});
```
![image](https://user-images.githubusercontent.com/22745515/50271609-2c719400-0470-11e9-92a5-8e6f70582253.png)

background partition
Laratables.php
I'm going to start from here, modify
![image](https://user-images.githubusercontent.com/22745515/50271751-9db14700-0470-11e9-84d6-60e8162cabf8.png)

I think you can enrich this plug-in by adding an update like an input event to each cell. 
Your plugin is excellent

**Comment by chongzia** [comment]
Ultimate solution
FilterAgent.php
Revised as follows
``    /**
     * Applies where conditions to the query according to search value.
     *
     * @param Class to customize query/data/logic
     * @param \Illuminate\Database\Query\Builder Query object
     * @param array Columns to be searched
     * @param string Search value
     * @param array Search Field Value
     *
     * @return \Illuminate\Database\Query\Builder Query object
     */
    public static function applyFiltersTo($class, $query, $searchColumns, $searchValue ,$searchFieldValue)
    {
        self::$class = $class;

        return $query->where(function ($query) use ($searchColumns, $searchValue,$searchFieldValue) {
                $query = self::applyFilter($query, $searchValue, $searchFieldValue, $searchColumns);
        });
    }

    /**
     * Applies filter condition for the table column.
     *
     * @param \Freshbitsweb\Laratables\QueryHandler Query object
     * @param string Search string
     * @param array Search Field Value
     * @param array Columns to be searched
     *
     * @return \Freshbitsweb\Laratables\QueryHandler Query object
     */
    protected static function applyFilter($query,  $searchValue,$searchFieldValue,$searchColumns)
    {
        foreach ($searchColumns as $key => $column)
        {
            if ($methodName = self::hasCustomSearch($column)) {
                return self::$class::$methodName($query, $searchValue);
            }

            if (isRelationColumn($column)) {
                return self::applyRelationFilter($query, $column, $searchValue);
            }

            $searchValue = '%'.$searchValue.'%';
            $query->orWhere($column, 'like', "$searchValue");
        }

        foreach ($searchFieldValue as $key => $val)
        {
            if (empty($val)) $field[$searchColumns[$key]] = $val;
        }

        foreach ($field as $key => $val)
        {
             $searchValue = '%'.$val.'%';
             $query->orWhere($key, 'like', "$val");
        }
    }``

QueryHandler.php
Revised as follows
` /**
     * Applies where conditions to the query according to search value.
     *
     * @param array Columns to be searched
     * @param string Search value
     * @param array Search Field Value
     *
     * @return void
     */
    public function applyFilters($searchColumns, $searchValue,$searchFieldValue)
    {
        $this->query = FilterAgent::applyFiltersTo($this->class, $this->query, $searchColumns, $searchValue,$searchFieldValue);
        $this->filteredCount = $this->query->count();
    }`

Laratables.php
Revised as follows
`/**
     * Applies conditions to the query if search is performed in datatables.
     *
     * @return void
     */
    protected function applyFiltersTo()
    {
        $searchValue = request('search')['value'];

        foreach (request('columns') as $key => $val){
            $searchFieldValue[$key] = $val['search']['value'];
        }
        if ($searchValue ||  $searchFieldValue) {
            $this->queryHandler->applyFilters($this->columnManager->getSearchColumns(), $searchValue,$searchFieldValue);
        }
    }`

I hope you can add Plug-in unit and write better than I do.

**Comment by chongzia** [comment]
awkward
No modification was successful

**Comment by gauravmak** [comment]
I see. you're talking about filter per column. I will consider it.

**Comment by ketbla** [comment]
Hi @gauravmak , I'm working on the application where individual column searching is mandatory. Are you planning on introducing support for it to laratables?

**Comment by gauravmak** [comment]
Yes, @Nutbeard I do plan to add support for this. Can't guarantee immediate update but pull requests are always welcome.

**Comment by chongzia** [comment]
Hopefully you'll be able to use this feature soon
Because that's the only way 
The datatable 
Only then has the foundation use significance truly

**Comment by gauravmak** [comment]
Sorry, @Nutbeard and @chongzia 

We have decided to skip this feature to keep the package simple. You may consider forking the repo and coding the feature. Thanks and best wishes.

**Comment by ffuentese** [comment]
It'd be cool if you added to the documentation that this feature is not available so that it doesn't waste people's time.

**Comment by lithin9** [comment]
Yes, please add that this doesn't work into the documentation. My coworker and I spent several hours trying to figure out why it wouldn't work.

**Comment by lithin9** [comment]
FYI for those still wanting to do this, you can accomplish it with the following really simple code:

```
public function listUsers(Request $request) {
	if($request->ajax()) {

		return Laratables::recordsOf(Users::class,
			function ($query) use ($request) {
				$columns = [
					array_column($request->columns, 'name'),
					array_column($request->columns, 'search')];
				foreach ($columns[0] as $key => $column) {
					if(!empty($columns[1][$key]['value'])) {
						$query = $query->where($column, '=', $columns[1][$key]['value']);
					}
				}

				return $query;
			});
	}

	return view('users/list');
}
```

**Comment by rattler72** [comment]
I dug a little deeper here and modified `Laratables.php`. My use case was this... I have a datepicker and wanted to filter so only records >= to the "start_date" would appear.

Here is what I did: 

**In the JS:**

```
// init a datatable... make sure the start date column is searchable
var myTable = $('#my-table').DataTable({... });

// when you pick a start date... do something
$("#my_startdate_picker").on("change.datetimepicker", function (e) 
{

    // get the date value from the picker
    var search_date_value = $("#my_startdate_picker").val();

    // invoke the search only on the column that has the start date, in this case "column 1" 
    myTable.column(1).search(search_date_value).draw();
});
```
**In the PHP Model code:**
```
// Create a custom search on the column, in this case a start date
public static function laratablesSearchStartDate($query, $searchValue)
    {
        // return records where the start date is on or after the picker value  
        return $query->where('start_at', '>=', $searchValue);
    }
```
**In the PHP Laratables.php:**
I changed this function...
```
protected function applyFiltersTo()
    {
        $searchValue = request('search')['value'];

        if ($searchValue) {
            $this->queryHandler->applyFilters($this->columnManager->getSearchColumns(), $searchValue);
        }
    }
```
To this...
```
protected function applyFiltersTo()
    {
        $searchValue = request('search')['value'];

        if ($searchValue) {
            $this->queryHandler->applyFilters($this->columnManager->getSearchColumns(), $searchValue);
        }

        // get all the columns
        $cols = request('columns');

        foreach ($cols as $col) {

            // if the column is searchable and has a value... apply a filter on it
            if ($col['searchable'] == true && !empty($col['search']['value'])) {

                $col_array = [$col['name']];
                $this->queryHandler->applyFilters($col_array, $col['search']['value']);
            }
        }
    }
```

In a nutshell, that was it... it is now searching on individual columns and invoked using the datatables `column().search()` functionality. I have not tested this to death or even considered the regex option, but this should work in most cases. I'll have to fork this unfortunately, but would love to see something like this implemented in the package.

**Comment by angusm73** [comment]
@rattler72, your solution works great for relational queries! Thank you!

I'm only using Laratables for two models so far. The remaining 5 are just client side datatables which need to be updated.

Will test regex more throughout this process and submit a pull request when done.
