### ISSUE TITLE
Laravel Scout ??

### ISSUE THREAD

**Issue by susonwaiba** [freshbitsweb/laratables#30]
Is there Laravel Scout support ??

**Comment by gauravmak** [comment]
Not yet. I will consider that.

Pull requests are always welcome. Thanks.

**Comment by gauravmak** [comment]
Sorry, @susonwaiba

We have decided to skip this for now as there is no demand for this from other users. Thanks.

**Comment by michaelnguyen2021** [comment]
just want to let you know that there is a demand for DataTables with Laravel Scout. There is one available package (https://github.com/yajra/laravel-datatables-scout) which has not been updated since July 2017. 

Would love to see this feature implemented
