### ISSUE TITLE
Use something other than `orWhereHas` in search

### ISSUE THREAD

**Issue by sentiasa** [freshbitsweb/laratables#31]
First time I used laratables - really nice work!

I have a question. For a relationship column (one to many), I built custom searches CustomColumn (for formatting), thus I needed to use a CustomSearch for this column also. Think it like "Channel has many subscribers".

CustomValue shows all subscribers. The initial load is 500ms (very good). However, when I search, 

```
public static function laratablesSearchSubsribers($query, $searchValue)
{
    return $query->orWhereHas('subscribers', function($q) use ($searchValue) {
        $q->where('cinema', 'like', '%'. $searchValue. '%');
    });
}
```

the whereHas causes 5.20s response time. In fact, I realised whereHas causes it to be very slow which I confirmed with my initial load.

```
public function getData() {
     // 3.36s
     return Laratables::recordsOf(Movie::class, function($q) {
         return $q->whereHas('subscribers');
     });

    // 400ms
    return Laratables::recordsOf(Movie::class, function($q) {
        return $q->where('subscribable ', true);
    });
}
```

But now, I fell in a pitfall for replacing `orWhereHas` in my query (because using it with %like% together causes very very slow response time. 

Can you guys think of any way to replace/optimize `orWhereHas`?

**Comment by gauravmak** [comment]
`whereHas` is provided by Laravel and I can't think of any other option. Do you have any suggestion?

**Comment by sentiasa** [comment]
I couldn't think of any other option either, but I think it might be faster if I could use it with `with()`. In fact, with the current setup it's not possible because we can't say `orWith()`. Or if I could give priority or order to queries that might have an effect.

**Comment by gauravmak** [comment]
We have to use `whereHas` to filter the records. `with` cannot be used to filter main table records.

**Comment by sentiasa** [comment]
I think `with` can query with eager loading like this
```
->with(['posts' => function ($query) {
    $query->where('title', 'like', '%first%');
}])
```
_Source: https://laravel.com/docs/5.7/eloquent-relationships#constraining-eager-loads_

or lazy eager loading
```
->load(['author' => function ($query) {
    $query->orderBy('published_date', 'asc');
}]);
```
_Source: https://laravel.com/docs/5.7/eloquent-relationships#lazy-eager-loading_

and suspect these might be faster than using whereHas. What do you think?

**Comment by gauravmak** [comment]
As I said, `with` cannot be used to filter main table records. Check [this](https://stackoverflow.com/a/30232227/3113599) for reference.

I will close the issue for now. Thanks.
