### ISSUE TITLE
Unable to get relation

### ISSUE THREAD

**Issue by msl2000** [freshbitsweb/laratables#32]
Hi

Whenever I try to retrieve relational data, it fails and gives the following errors:

error: "The 'image.source' column is not in the select column list. Please add it to the select columns or make it - orderable : false"

The relationship is a hasOne and checked that the relationship worked fine. The relationship is:

```
class Sponsor extends Model
{
    protected $table = 'sponsors';
    protected $with = ['image'];
....

public function image(){
        return $this->hasOne(Image::class, 'id', 'image_id');
    }
```
In the dataTable trying to pull the data as:

```
    columns: [
.....
                 {
                    name: 'image.source', render: function (data, type, row) {
                    return '<img src="' + data + '" class="circle circle-xs">';
                    },
                    orderable: false
                },

```

**Comment by gauravmak** [comment]
It is possible that the Datatables is requesting to order the records by the relationship column even when you have specified that it is not orderable.

Have you specified the [default sorting option](https://datatables.net/examples/basic_init/table_sorting) in the Datatables config? Its key is `order`.

**Comment by msl2000** [comment]
Hi

I did not specify any columns default sorting. Is it necessary?

**Comment by gauravmak** [comment]
Okay, can you please share the ajax request that datatables is making to load the table data when you open the page?

You can copy that from the Network tab of the browser.

**Comment by gauravmak** [comment]
Datatables sorts the records by the first column if not specified.

Try defining the default sorting option for other column or change column order. Thanks.

**Comment by allandereal** [comment]
Just realized that, the problem is because you are listing the columns starting with the relationship. The first column shouldn't be a relationship in the columns array. The relationship should probably come second
