### ISSUE TITLE
Relationship column name not found in select list

### ISSUE THREAD

**Issue by Bhagwan00** [freshbitsweb/laratables#33]
columns: [
                { name: 'committee.name',  orderable: false },
                { name: 'school'},
                { name: 'firstname'},
                { name: 'control', orderable: false, searchable: false},
                { name: 'message_flag', visible: false},
                { name: 'committee_id', visible: false},
            ]

**Comment by hirenkeraliya** [comment]
Provide more details.

**Comment by gauravmak** [comment]
I guess this is same as issue #32 
Please check and update there.

**Comment by ghost** [comment]
@Bhagwan00 It's happen when you try to use the relationship column at first
But if you change the order it will work

columns: [
{ name: 'school'},
{ name: 'committee.name', orderable: false },
{ name: 'firstname'},
{ name: 'control', orderable: false, searchable: false},
{ name: 'message_flag', visible: false},
{ name: 'committee_id', visible: false},
]
** or something else

**## I don't know why. But I face same problem**

**Comment by gauravmak** [comment]
That means - Datatables sorts the records by the first column if not specified.

**Comment by agasigp** [comment]
> @Bhagwan00 It's happen when you try to use the relationship column at first
> But if you change the order it will work
> 
> columns: [
> { name: 'school'},
> { name: 'committee.name', orderable: false },
> { name: 'firstname'},
> { name: 'control', orderable: false, searchable: false},
> { name: 'message_flag', visible: false},
> { name: 'committee_id', visible: false},
> ]
> ** or something else
> 
> **## I don't know why. But I face same problem**

Thanks for the solution! I have same problem with you. Problem was solved by changing order of column like you said.
