### ISSUE TITLE
Nested Arrays

### ISSUE THREAD

**Issue by PhilBellwood** [freshbitsweb/laratables#35]
Hi

I am having some issues with arrays, I have a relational query that fetches the results and returns as an array.

I have tied many methods to access the data that is within the array but can not get it to work.
This is how the results are returned.
4: {name: "Bob Smith"}
name: "Bob Smith"

This is the Datatable line
 { name: 'assignedLink.name', orderable: false },

Any advice would be helpful.

Kind regards

Phil

**Comment by gauravmak** [comment]
Phil,

As per [this example](https://github.com/freshbitsweb/laratables#custom-columns), you can also customize the value of the relationship column - `public function laratablesAssignedLinkName()`

Inside the function, you can use `$this` to access data.
