### ISSUE TITLE
Pivot Table with no PK - Deselecting 'id' from Query

### ISSUE THREAD

**Issue by ervansanjaya** [freshbitsweb/laratables#38]
I have many to many relationship where its pivot has extra attribute than foreign key of both many tables.

When I try to fetch the data using Laratables, its resulting 

` Column not found: 1054 Unknown column 'id' in 'field list'`

The reason I don't want to select is because my pivot table has no ID, it doesnt matter right?

My question is how I can ignore that 'id' from the pivot table so I can just select each foreign key and the extra attribute from my pivot table?

When I try to add property to my pivot model

`protected $primaryKey = null;`

It results:

`Column not found: 1054 Unknown column '' in 'field list' (SQL: select ``, `name`,`

Can I do this without ID? Or having ID on a pivot table become a must?

-------------------------------------------------------------------------------------------------

I tried to load the pivot using many table using `withPivot()`, but I'm having issue here that is very strange and can't resolve it currently, if any of you have experience using `withPivot()` I'll be grateful if you would share it here to me. 

The error found when I access other many table is :
`Property [id] does not exist on this collection instance.`

Thank you.

**Comment by gauravmak** [comment]
I haven't put pivot table data in Datatables before.

Are you trying to get the pivot data directly? i.e. Using the model of the pivot table to prepare the datatables data? Or fetching the many to many relationship from a model?

**Comment by ervansanjaya** [comment]
> I haven't put pivot table data in Datatables before.
> 
> Are you trying to get the pivot data directly? i.e. Using the model of the pivot table to prepare the datatables data? Or fetching the many to many relationship from a model?

Thank you for your response @gauravmak 

I tried both of it.

1. Using the model of pivot table, it requires to have ID on the pivot table, while I didn't have one. 

2. Using the many to many relationship, I'm having issue on accessing my extra attribute in my pivot table, i tried `using()` + `withPivot('extraAttributeColumnName')` but it said property `extraAttributeColumnName` doesn't exist.

My example data is I have two many-to-many table `items` and `users` and it has `item_user` that contains `quantity`, and two referencing foreign key to `items` and `users`.

I want to be able to display in my datatable as such:

`User Name | Item Name | Quantity`

**Comment by gauravmak** [comment]
You can treat quantity as a [custom column](https://github.com/freshbitsweb/laratables#custom-columns).

Then, you can use [laratablesQueryConditions()](https://github.com/freshbitsweb/laratables#controlling-the-query) to load the relation.

**Comment by ervansanjaya** [comment]
> You can treat quantity as a [custom column](https://github.com/freshbitsweb/laratables#custom-columns).
> 
> Then, you can use [laratablesQueryConditions()](https://github.com/freshbitsweb/laratables#controlling-the-query) to load the relation.

But how about the issue I have which is the query keep selecting ID of my pivot table when it actually didn't have one?

I only 

```
columns: [
                { title: 'Use Name', name: 'user.name' },
]
```

But it keeps selecting 'id' of `item_user` table.

**Comment by gauravmak** [comment]
I will need to check this.

**Comment by ervansanjaya** [comment]
Thank you so much @gauravmak

**Comment by ervansanjaya** [comment]
@gauravmak I ended up 'faking' my $primaryKey attribute on my pivot model to finally able to show my desired output. So I just named my pivot table's primary key with one column name of the referencing key, and voila, it's all solved.

But I'm hoping that this will be fixed soon (if it's actually a bug).

Thank you.

**Comment by gauravmak** [comment]
Ervan,

> My example data is I have two many-to-many table items and users and it has item_user that contains quantity, and two referencing foreign key to items and users.
> 
> I want to be able to display in my datatable as such:
> 
> User Name | Item Name | Quantity

I didn't get how you want to display the data here. A user can have multiple items. You need to customize the value to maybe display them comma-separated or something. Example - 

```
    /**
     * Returns comma-separated name for the datatables.
     *
     * @return string
     */
    public function laratablesItemsName()
    {
        return $this->items->pluck('name')->implode(', ');
    }
```

I just tried that and it worked for me. Reply if you're still facing any issues.
