### ISSUE TITLE
HTML in column

### ISSUE THREAD

**Issue by aleex1848** [freshbitsweb/laratables#39]
First of all thank you for this nice package. I was able to significantly increase page load speed with this package!
One question:
I often use a table's last column to display some buttons like show, edit, delete.
How can i achieve this  using your package?
In HTML i only specify the table header, the table body is completely handled by the client-side js code (the columns array), right? So how to put some HTML in the table body?
Cheers

**Comment by ervansanjaya** [comment]
Hi, Alex @aleex1848

You can do it using `laratablesCustomColumn($object)` and if needed `laratablesAdditionalColumns()` as I explained here

https://github.com/freshbitsweb/laratables/issues/28

Hopefully it helps

**Comment by aleex1848** [comment]
Hi @ervansanjaya ,

exactly what i was looking for. Works like a charm. Thank you!!
