### ISSUE TITLE
laratablesRowClass in custom table class

### ISSUE THREAD

**Issue by CJau** [freshbitsweb/laratables#42]
Hi, I've created a custom class to store the Laratables logic, so my model is cleaner.

When I try to add the laratablesRowClass function to my custom class to add custom CSS class names to table rows, I receive an error that CompletedAudit->laratablesRowClass is undefined.  

If I then _also_ add a laratablesRowClass function to the model, and put my logic in there, the class names are added.

If I then _remove_ the laratablesRowClass from my custom Laratables class, but leave it in the model, it stops working as if it isn't even there.

Is this intended behaviour, or should I be able to put a function called laratablesRowClass in my custom Laratables class and it is all picked up from there?

Controller method:
~~~
   public function completed_audits_datatables() {
      return Laratables::recordsOf(CompletedAudit::class,CompletedAuditsTable::class);
    }
~~~

Laratables class:
~~~
<?php
  namespace App\Laratables;

  use App\CompletedAudit;

  class CompletedAuditsTable 
  {
    ...

    /**
     * Bug in laratables? - needed as stub here and function in model to be picked up.
     */
    public function laratablesRowClass() { }
  }
~~~

Model:
~~~
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class CompletedAudit extends Model implements Auditable
{
    ...

    public function laratablesRowClass() {
      $class = $this->type->colour ? $this->type->colour.' lighten-4' : null;
      return $class;
    }
}
~~~

**Comment by gauravmak** [comment]
Hi,

You're right. It's a bug. Thank you for pointing this out. We will work on at the earliest.

**Comment by gauravmak** [comment]
Just to note - due to the current workload, we are not getting enough time to make updates this. We would happily welcome a PR for this.

**Comment by CJau777** [comment]
Happy to try figure it out and submit a PR if you can point me in the right direction for where these are defined?
________________________________

**Comment by gauravmak** [comment]
Fixed with the new release, thanks.
