### ISSUE TITLE
SSP enabled: show all rows

### ISSUE THREAD

**Issue by zxckoko** [freshbitsweb/laratables#43]
Hi,

How do we make use of `pageLength` parameter in SSP Laratables to return all DB rows? I have it working fine in plain DT... but, when implemented in Laratables, the 'All' `pageLength` returns an SQL syntax error. It's something like this:

"select `id`, `product_base_id`, `sku`, `name`, `description`, `quantity`, `eol_status` from `rs_product_variants` where `rs_product_variants`.`deleted_at` is null order by `sku` desc offset 1"

That's the query thrown by Laratables, and by removing the `offset 1` value (manual query), fixes the problem. What am I missing? I'm trying to expose all records to make use of DT export buttons.

Thanks!

**Comment by pamekar** [comment]
I got the same error 

`select id, isrc, artist, product_title, container_title, label, country, total_plays, revenue, start_at, end_at from records where user_id = 1 order by id asc offset 0
[2019-04-11 21:15:31] [42000][1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'offset 0' at line 1
[2019-04-11 21:15:31] [42000][1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'offset 0' at line 1`

Is there a way around this?

**Comment by gauravmak** [comment]
Thank you for pointing this out.

The new PR #47 is for the same I think. Will need to tinker about all use cases before we merge this in.

**Comment by gauravmak** [comment]
Fixed with latest update.
