### ISSUE TITLE
Custom column with relation

### ISSUE THREAD

**Issue by yuliantosb** [freshbitsweb/laratables#44]
Hello, I have some issue here, when I want to add new Column with format with a relationship field, I got an error, that the relationship is null.

```
public function User 
{
     return $this->belongsTo('App\User');
}

public function laratablesFullName()
{
        return $this->user->first_name.' '.$this->user->last_name;
}
```

the error said

`Trying to get property 'first_name' of non-object`

do I do something wrong?, sorry for bad English

**Comment by breaktag** [comment]
I have a similar issue:

```
public function savedBalances 
{
     return $this->hasMany('App\SavedBalance');
}

public function laratablesMemberBalance()
{
        return $this->savedBalances->sum('top_ups") - $this->savedBalances->sum('spend");
}
```

Anyway I can do this? And not have to select a `member_balance` column in my query?

**Comment by gauravmak** [comment]
@yuliantosb Have you loaded the `user` relationship? There are 2 days to do this:
- Either any of the columns that you have specified on the client side is from the user table (for example, `user.name`)
- Or you can use [Controlling the query](https://github.com/freshbitsweb/laratables#controlling-the-query) feature to tell Laratables to load the relationship for you.

**Comment by gauravmak** [comment]
@breaktag Please read the comment above.

**Comment by SanderMuller** [comment]
You have to select the key on which a relation is joined. 

For example, `Book` with a relation to an `Author` where `Book` has column `author_id` to reference the author.

You want to use the name of the author in a custom function, then you have to add `author_id` to the select in laratablesAdditionalColumns, as explained here https://stackoverflow.com/a/52557008
