### ISSUE TITLE
Selecting/Displaying a custom column

### ISSUE THREAD

**Issue by breaktag** [freshbitsweb/laratables#45]
Hello.

I was wondering if there is a way to select a custom column to be displayed on Datatables.

In MySQL I currently have this statement, whereby I am selecting a column called `additional`, performing a conditional on it and aliasing it as `downloaded_app`:

```
SELECT IF (additional LIKE '%device_information%', 'Y', 'N') AS downloaded_app
```

In Eloquent I would do something along the lines of `DB::raw('IF (...) AS downloaded_app')`

I am just wondering how I could incorporate this custom column into Laratables. 

At the moment I am receiving an unknown column error: `Column not found: 1054 Unknown column 'downloaded_app' in 'field list'`

Cheers

**Comment by gauravmak** [comment]
Hi Ben,

You can do that using our [Selecting additional columns](https://github.com/freshbitsweb/laratables#selecting-additional-columns) feature. Something like:

```php

use Illuminate\Support\Facades\DB;
...

/**
 * Additional columns to be loaded for datatables.
 *
 * @return array
 */
public static function laratablesAdditionalColumns()
{
    return [DB::raw("IF (additional LIKE '%device_information%', 'Y', 'N') AS downloaded_app")];
}
```

If you are going to request `downloaded_app` column directly from the client, be sure to add a [custom column function](https://github.com/freshbitsweb/laratables#custom-columns) to tell Laratable not to search for `downloaded_app` column in the table directly.

I hope it helps.

**Comment by breaktag** [comment]
@gauravmak Excellent! Thank you, that is just what I need
