### ISSUE TITLE
Comparison to yajra/laravel-datatables?

### ISSUE THREAD

**Issue by hailwood** [freshbitsweb/laratables#5]
Hey @gauravmak,

Could you add a comparison to https://github.com/yajra/laravel-datatables please?
Been using the previous package in quite a few projects and have had no issues, but competition/alternatives are always good, so I'd be interested in knowing "Why would I use this package over yajra's package?"

**Comment by gauravmak** [comment]
Hi Matthew,

I had used that package myself a year ago. It works great. And quite stable and mature by the time.

I just wasn't much comfortable with its style of defining columns and other things on an object in a single call. And documentation.

So, I developed a custom solution and used it in a couple of projects before converting it into this package which may be useful for people like me.

Currently, this package does provide all the basic functionalities. but it doesn't do anything which yajra's package isn't doing so I didn't add a comparison.

Thanks.
