### ISSUE TITLE
Handle custom request data

### ISSUE THREAD

**Issue by breaktag** [freshbitsweb/laratables#50]
Hello,

I am working on a project using DataTables which means I need to use custom filters, along with server side pagination. These filters are

**1. Show Inactive members" / "Show active members:**
Currently a checkbox which sets a value on the request `show_inactive = true|false`

**2. last Used Since / Upto**
```
last_used = "20/02/2019 10:38"
last_used_operator = >= || <=
```

At the moment I am using the `laratablesQueryConditions()` method, with logic in side to look at the `request()` values, and perform the appropriate conditions on the query but just wondered if there was a better way?

Great package by the way!

Thanks

**Comment by gauravmak** [comment]
Ben,

Even I can't think of any other way to do the same :)

Good to know that the package is useful for you, Cheers.
