### ISSUE TITLE
Feature request: sorting by custom calculated value

### ISSUE THREAD

**Issue by breaktag** [freshbitsweb/laratables#51]
Hello,

I would like to be able to use datatables sorting with a column that doesn't exist in my database table. The column is actually a relationship column from another table on a one to many relationship. On the "many" side of the relationship I calculate the sum of the column and that is my value, id like to order on.

To give context:

- I am showing a list of members
- A member has many balance transactions (imagine like a bank statement)
- The members current balance is the sum of the balance column on the above relationships "many"
- I'd like to order by this calculated/ related column

Cheers

**Comment by gauravmak** [comment]
Hey Ben,

Laravel Eloquent fires 2 separate queries to fetch data from different tables instead of making a join query. This prevents us from ordering the records using a column from the second table.

In the future, we could allow developers to do joins on the main table for the same.

**Comment by DorelBesliu** [comment]
> Hey Ben,
> 
> Laravel Eloquent fires 2 separate queries to fetch data from different tables instead of making a join query. This prevents us from ordering the records using a column from the second table.
> 
> In the future, we could allow developers to do joins on the main table for the same.

@gauravmak Could you implement sortBy('relation.column') and sortByDesc('relation.column') ?

**Comment by CJau** [comment]
Not sure if it's useful or relevant, and probably not intended use, but I have used the existing `laratablesQueryConditions($query)` function successfully to do joins on the main table and then able to search/order as a result.

Perhaps all that's needed is an update to the documentation showing how this can be done?

**Comment by gauravmak** [comment]
@CJau777 Can you please share the example code?

**Comment by CJau** [comment]
In my case we have a table of CompletedAudit models.  CompletedAudits belong to an Instructor (belongsTo/hasMany), and an Instructor belongs to a User (belongsTo/hasOne relationship).  I needed to display/search/sort CompletedAudits by User first/surname.

Did the joins as below:
```
public static function laratablesQueryConditions($query) {
      $q = $query
        ->join('instructors','instructors.id','completed_audits.instructor_id')
        ->leftJoin('users as iu','instructors.user_id','iu.id')
        ->select([
          'iu.firstname as instructor_firstname',
          'iu.surname as instructor_surname',
        ]);
      return $q;
    }
```
Then sorting/searching:
```
    public static function laratablesOrderRawInstructor($direction) {
      return 'iu.firstname '.$direction.', iu.surname '.$direction;
    }
    public static function laratablesSearchInstructor($query, $searchValue) {
      return $query->orWhere('iu.firstname', 'like', '%'. $searchValue. '%')
        ->orWhere('iu.surname', 'like', '%'. $searchValue. '%');
    }
```
Happy to try generalise to a case with just one join for simplicity and do a PR to the readme if that helps?

**Comment by gauravmak** [comment]
@breaktag Please try this as suggested by @CJau777 and let us know how it goes, thanks.

**Comment by breaktag** [comment]
Hi @gauravmak , @CJau 

The below worked for me, instead of using Laravel relationships (Ordered_Item HasOne Tab in my example below), I used joins and grabbed the column in my select which allowed me to sort by. `tab_name`:

```
public static function laratablesQueryConditions($query)
{
        $query = $query
            ->leftJoin('tabs as t', 't.tab_id', 'ordered_items.tab_id')
            ->select([
                'ordered_items.tab_id',
                't.tab_name as tab_name'
            ]);

        return $query;
}
```

It's worth noting I am still having trouble sorting on another column which is not a relationship but a computed column on the ordered_item Model. I have however removed the ability to sort on my application but it would be good to know if there is a way to use Laratables to sort on a Model Accessor 

I want to be able to sort by **my_custom_col** on the OrderedItem model via Laratables: 

```
class OrderedItem extends Model {
   public function getMyCustomColAttribute($value) {
      //return do something with $value  
   }
}
```

Thank you
