### ISSUE TITLE
[bug] Customizing column values with dedicated class

### ISSUE THREAD

**Issue by Yahav** [freshbitsweb/laratables#52]
Hey

I utilize a dedicated class for the model datatables:

`Laratables::recordsOf(Show::class, ShowDatatables::class);`

at my ShowDatatables class i have 

`public function laratablesArchivedAt()`

but laratables doesn't seem to recognize it. i'm getting the following error:

> Call to undefined method App\Models\Show::laratablesArchivedAt()

The problem is at \Freshbitsweb\Laratables\RecordsTransformer::getColumnValue

` if ($methodName = $this->customisesColumnValue($columnName)) {
            return $record->$methodName();
        }`

should be: 

` if ($methodName = $this->customisesColumnValue($columnName)) {
return $this->class::$methodName($record);
        }`

**Comment by gauravmak** [comment]
Correct @Yahav 

The custom class implementation has [some bugs](https://github.com/freshbitsweb/laratables/issues/42).
It needs to be re-written properly. We will be able to hopefully re-write that soon.

**Comment by gauravmak** [comment]
We will update [this issue](https://github.com/freshbitsweb/laratables/issues/42) once this has been fixed.
