### ISSUE TITLE
Relationship from Another Relatonship Table

### ISSUE THREAD

**Issue by hadyandev** [freshbitsweb/laratables#56]
Hello, I wanna ask. Is it possible to have relationship from another relationship table?
Let's say I have 3 tables: Table A, Table B, and Table C.
Table A related to Table B, and Table B related to Table C.
So, with that kind of relationship, it's possible for me to display Table B data on Table A, and display Table C data on Table B using Laratables.
Then, here comes my question. **_Is it possible to display Table C data on table A using Laratables?_**
Because Table A related to Table B, and Table B related to Table C.

Anyway, thanks a lot for creating Laratables. It helps me a lot. :)

**Comment by gauravmak** [comment]
Hi @hadyandev 

As per the Readme file,

> `Note` - The package does not support [nested relationships](https://github.com/freshbitsweb/laratables/issues/6) yet. You can utilize the custom column feature to get the nested relationship data but make sure that you [eager load](https://github.com/freshbitsweb/laratables#controlling-the-query) the relationship records.

you may use custom column feature.
