### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by ibrahem-kamal** [freshbitsweb/laratables#59]
i am trying to use laratables with mongodb and jessenger but am getting this error 

Undefined index:
at         $orderColumn = $requestedColumnNames[$order[0]['column']];
in           public function getOrderColumn()

**Comment by gauravmak** [comment]
Hi @ikiv6 

I am sorry we are using Eloquent in the package so MongoDB wouldn't work out of the box.

**Comment by Thedigit** [comment]
Hi,

is there a road map or a solution for this to work with Jessengers Mongo?
