### ISSUE TITLE
Non-static methods for changing column data in custom classes always call base class instead of custom class

### ISSUE THREAD

**Issue by robkerr1992** [freshbitsweb/laratables#60]
From controller:

    public function retrieveOrderTransactions()
    {
        return Laratables::recordsOf(Transaction::class, OrderTransactions::class);
    }

From class OrderTransactions (custom class holding laratables custom funtions):

    public static function laratablesAdditionalColumns()
    {
        return ['id'];
    }

    public static function laratablesCustomId($transaction)
    {
        return 'ID: ' . $transaction->id;
    }

This will correctly yield "ID: id" for each row.

If you change the laratablesCustomId() function to this:

    public function laratablesId()
    {
        return 'ID: ' . $this->id;
    }

You get this error:

`Call to undefined method App\Models\Transaction::laratablesId()`

This is because in laratables/src/RecordsTransformer.php on line 81:

        if ($methodName = $this->customisesColumnValue($columnName)) {
           return $record->$methodName();
        }

`$record` is always an instance of App\Models\Transaction (base class) and not an instance of OrderTransactions (my custom class) even though in 
`$this->customisesColumnValue($columnName)` the package checks to see if the desired method exists on the custom class (`$this->class`).

     protected function customisesColumnValue($columnName)
     {
        $methodName = camel_case('laratables_'.$columnName);

        if (method_exists($this->class, $methodName)) {`
            return $methodName;`
        }

        return false;
     }

I'm not sure if this is a bug or only custom methods are supposed to be used on custom classes. Is this how the package is intended to work?

Any help would be greatly appreciated. Thanks.

**Comment by gauravmak** [comment]
Thanks for the details, Robert.

Yes, this is a [known bug](https://github.com/freshbitsweb/laratables/issues/42). We will try to solve this at the earliest.

**Comment by robkerr1992** [comment]
@gauravmak if you are interested in help I can look into submitting a pull request?

**Comment by gauravmak** [comment]
@robkerr1992 Thanks for the offer.

I got some time today morning to crack this. Just published a new release with the fix.
