### ISSUE TITLE
Error after instalation

### ISSUE THREAD

**Issue by lfrichter** [freshbitsweb/laratables#61]
After install it, I received this error, do you know what can be?

PHP Parse error:  syntax error, unexpected '=' in /var/www/vendor/freshbitsweb/laratables/src/helpers.php on line 46

**Comment by gauravmak** [comment]
Hi @lfrichter 

Which version of PHP are you using?

**Comment by lfrichter** [comment]
Hi, I already gave up use it.
However, to you know, I was using PHP 7.0

**Comment by gauravmak** [comment]
Thanks for the info @lfrichter 

`[$relationName, $relationColumnName] = getRelationDetails($columnName);`

We are using [array destructuring](https://stitcher.io/blog/array-destructuring-with-list-in-php) in that file. And it is supported PHP 7.1 onwards I guess.

Have a great day.
