### ISSUE TITLE
case-insensitive search?

### ISSUE THREAD

**Issue by DustinReagan** [freshbitsweb/laratables#62]
Great job!

I noticed, however, that by default the search is case-sensitive.  Is there any config option, etc which will use a case-insensitive search?

**Comment by gauravmak** [comment]
Hey Dustin,

The search uses MySQL like where condition which is case-sensitive by default.

**Comment by gauravmak** [comment]
Seems like there may be different defaults as per MySQL version. I just tested in the [demo](https://laratables.freshbits.in/) and the search is case insensitive.

Please confirm on your end as well.

If the search is case sensitive in your environment, please share MySQL version details. Thanks.

**Comment by DustinReagan** [comment]
Sorry for the delay.  I am using a postgres backend, and the search is case-sensitive by default.  I am able to work around this by adding custom laratableSearch functions for each field I want to search, but this is a bit of a pain:

`public static function laratablesSearchNickname($query, $searchValue) {
        return $query->orWhere('nickname', 'ilike', '%'. $searchValue. '%');
  }`

**Comment by gauravmak** [comment]
I can understand that but different databases would have different ways of dealing with case-insensitive searches. Eloquent does not offer a way to control that yet. So, how can give config option to users?
