### ISSUE TITLE
'Array to String Conversion' 500 Error

### ISSUE THREAD

**Issue by jkhamler** [freshbitsweb/laratables#63]
Hi all,

I am desperately trying to get this to work, using the most basic vanilla code. My AJAX controller is returning the following error:

`Array to string conversion
/var/www/test-october/vendor/october/rain/src/Html/BlockBuilder.php line 80`

Here is my table:

<table id="settlementLogs" class="display settlement-log-table" style="width:100%">
    <thead>
    <tr>
        <th>Date/time</th>
        <th>User</th>
        <th>Event</th>
    </tr>
    </thead>
</table>

Here is my JS:

`    $('#settlementLogs').DataTable({
        serverSide: true,
        processing: true,
        responsive: true,
        ajax: ajaxUrl,
        columns: [
            {name: 'created_at'},
            {name: 'user_id'},
            {name: 'event'}
        ]
    });
`

Here is my controller action:

`
    public function ajax()
    {
        return Laratables::recordsOf(TempoAudit::class);
    }`

This is driving me crazy. The stack trace is just a load of low level system stuff that isn't any use. My setup is Laravel 5.5 within an October CMS app. No problems using DataTables so far.

Help greatly appreciated - thanks!

**Comment by arturskovrigo** [comment]
error 500 means that there is a problem on the server, probably on your controller, to see a more detailed explanation of the error  include this:  use Illuminate\Support\Facades\Log;
and then navigate to storage/logs. If using linux, write this into the terminal: tail -f laravel[todays date] This should help you diagnose your problem.

**Comment by jkhamler** [comment]
Thanks for the reply @arturskovrigo 

I know what a 500 Error is ;-)

It turns out that LaraTables clashes with October CMS because there is a call deep down to echo something that it expects to be a string, not an array.

The solution was, I just constructed my own JSON response manually without the library.

`
public function ajax($runSettlementId)
    {
        $length = Request::get('length');
        $draw = Request::get('draw');
        $search = (string) Request::get('search')['value'];

        /** @var RunSettlement $runSettlement */
        $runSettlement = RunSettlement::find($runSettlementId);

        $allLogs = $runSettlement->getLogs();
        $allLogsCount = $allLogs->count();

        if ($search !== '') {
            $allLogs = $runSettlement->filterLogs($allLogs, $search);
        }

        $jsonLogs = [];

        foreach ($allLogs->slice(0, $length) as $index => $log) {
            /** @var $log TempoAudit */
            $jsonLogs[] = [
                $log->created_at->format('Y-m-d h:i:s'),
                $log->getTempoUsername(),
                $log->event,
                $log->auditable_type,
                json_encode($log->old_values),
                json_encode($log->new_values)
            ];
        }

        return response(
            json_encode([
                'draw' => $draw,
                'recordsTotal' => $allLogsCount,
                'recordsFiltered' => $allLogsCount,
                'data' => $jsonLogs,
            ])
        )->withHeaders([
            'Content-Type' => 'text/json; charset=utf-8'
        ]);
    }
`
