### ISSUE TITLE
Getting the actual value of what i selected

### ISSUE THREAD

**Issue by arturskovrigo** [freshbitsweb/laratables#64]
I have a table, on of the columns is username, it is the first column.
i use this code to retrieve the values, because i saw this being used in the online example.
```
$('#users-table').on('click', 'tr',function(){
  alert(Object.values($(this)));
});
```
The problem is that the alert shows this: [object HTMLTableRowElement],[object HTMLTableRowElement],1 
How could i get a specific value from the table? I want to use it further in a variable, redirect to a different site, and so on.

**Comment by gauravmak** [comment]
I'm certainly not a datatables expert.

A quick search led me here - https://datatables.net/reference/api/row().data()

**Comment by arturskovrigo** [comment]
> I'm certainly not a datatables expert.
> 
> A quick search led me here - https://datatables.net/reference/api/row().data()

THANk YOU, i wasted 3 hours on this, people like you are what keep the earth turning, seriously, you are the best.
