### ISSUE TITLE
Pass additional parameter from controller to laratables custom class

### ISSUE THREAD

**Issue by keithsk** [freshbitsweb/laratables#69]
Dear Sir,

Possible pass additional parameter($status_name) from controller to laratables custom class query condition? Appreciated for your advice. Thanks.

Controller
```
public function datatables()
{
     $status_name = Input::get('status_name');
     return Laratables::recordsOf( Order::class, OrderLaratables::class, $status_name);
}
```

Custom Class
```
class Order
{
    public static function laratablesQueryConditions($query)
    {
        return $query->where('status', $status_name);
    }
}
```

**Comment by gauravmak** [comment]
@keithsk No, there is no direct way to pass parameters to the custom query method.

In this example, you seem to be using the value of an input. You can get the value of a request/input parameter in your custom class (or any other Laravel class) as well :)

**Comment by keithsk** [comment]
Great, thanks a lot for advice. ;)
