### ISSUE TITLE
Make a dediacted class for the tables

### ISSUE THREAD

**Issue by shadoWalker89** [freshbitsweb/laratables#7]
Hi,

How about making a class for the tables something like `UsersTable` that will contain the methods for extra columns and every other customization.
This will leave the model clean and avoid cluttering it with dataTable methods

**Comment by gauravmak** [comment]
I agree with you @shadoWalker89.

I have been using a trait in a couple of my projects just to keep models clean. That is not the best way. I like your idea and will surely work on it once I get some time.

I may decide to develop this in a way where developers can continue with current way or add a new class. Thanks.

**Comment by mgsmus** [comment]
I was thinking the same thing
```
// app/User.php
public $laratables = \App\Laratables\UserTable::class,
```

**Comment by gauravmak** [comment]
Added an option to let user specify the class in `recordsOf()` method. Thanks.

```php
use App\User;
use Freshbitsweb\Laratables\Laratables;
use App\Laratables\User as UserLaratables;
...
return Laratables::recordsOf(User::class, UserLaratables::class);
```

**Comment by Yahav** [comment]
This doesn't seem to cover the ["Customizing column values"](https://github.com/freshbitsweb/laratables#customizing-column-values) 
I'm getting:

> Call to undefined method App\Models\Show::laratablesArchivedAt()
