### ISSUE TITLE
Using the laratablesAdditionalColumns() function to merger OneToMany relation column?

### ISSUE THREAD

**Issue by northify** [freshbitsweb/laratables#76]
I'm using the laratablesAdditionalColumns() an want to know if there is a way to merge in a column form a OneToMany relation.

Here I bring in the manager_id
~~~
public static function laratablesAdditionalColumns()
    {

        return ['id', 'name', 'first_name', 'last_name', 'title_id', 'location_id', 'manager_id', ];

    } 
~~~

This gives me something like...
~~~
{
    "draw": 2,
    "recordsTotal": 441,
    "recordsFiltered": 441,
    "data":[
        {
            "0": First,
            "1": Last,
            "2":{
                "id": 10,
                "first_name": First2,
                "last_name": Last2,
                ...

            }

        }
    ],
}
~~~

How can I merger the column "2", "first_name" for example?

**Comment by gauravmak** [comment]
Hi

A couple of examples from [the demo](https://laratables.freshbits.in/) can help you here:

1) `Customize Column` example demo merge `first_name` and `last_name`
2) `Many To Many` example uses the `custom column` feature to manually fetch relationship data and merge it (joining the roles by a comma in the example)

Thanks.

**Comment by northify** [comment]
Hi, Ok thanks. I was able to get this now, however I when I use the laratablesOrder function there is an issue.

In my datatable I list users. I can order these uses by last_name. These users have managers that are related on the same users table by the manager_id. I need to be able to order by users column and managers column, both by last_name. I can order by users last name fine, but get errors when trying by managers last name.

~~~
columns: [
	{name: 'name'},
	{name: 'username'},
	{name: 'status', orderable: false, searchable:false},
	{name: 'manager.last_name',searchable:false},
~~~

~~~
public static function laratablesOrderManagerLastName()
    {
        return 'manager.last_name';
    }
~~~

~~~
public static function laratablesAdditionalColumns()
    {
        return ['id', 'name', 'first_name', 'last_name', 'title_id', 'location_id', 'manager_id', 'supervisor_id','manager.last_name'];
    }
~~~

If I add `'manager.last_name'` to the laratablesAdditionalColumns() function I get this error"
Column not found: 1054 Unknown column 'manager_id.last_name' in 'field list' 

If I leave it out I get there error:
DataTables warning: table id=k_table_1 - The 'manager.last_name' column is not in the select column list. Please add it to the select columns or make it - orderable : false

**Comment by gauravmak** [comment]
Good to know that it worked :)

For sorting, as mentioned in #25, it is not possible to use the relationship column in the sorting because Laravel uses 2 different queries to fetch data.
