### ISSUE TITLE
Custom Number Column

### ISSUE THREAD

**Issue by AzSamim** [freshbitsweb/laratables#77]
Thank you from your Nice package This is awesome.
But I have a problem with numbering of my rows because some times i can't number my rows with Id field so i want to customize my numbering. for example in a simple table i have like the below code.
@foreach($data as $item=>$row)
     <tr>
            <td>{{ ++$item }}</td>
            <td>{{ $row->name }}</td>
            <td>{{ $row->last_name }} </td>
            <td>{{ $row->email }} </td>
     </tr>
@endforeach

Pleas help me that how i can do some staff like that? Thank you.

**Comment by gauravmak** [comment]
Good question. You can use the custom column and modify collection features to get the serial number type of functionality.

Client side code:
```
{ name: 'serial_no', orderable: false, searchable:false },
```

Server side code:
```
/**
 * Sets the serial number column value for each user.
 *
 * @param \Illuminate\Support\Collection
 * @return \Illuminate\Support\Collection
**/
public static function laratablesModifyCollection($users)
{
    return $users->map(function ($user, $key) {
        $user->serial_no = $key + 1 + request()->input('start');
    
        return $user;
    });
}

/**
 * Returns the custom column serial number value for table.
 *
 * @param \App\User $user
 * @return string
*/
public static function laratablesCustomSerialNo($user)
{
    return $user->serial_no;
}
```

**Comment by ahmadshobirin** [comment]
Sory, I tried it, but column "serial_no" is undefined. whether the column should be in the table?

thanks.

**Comment by gauravmak** [comment]
@ahmadshobirin I made a mistake in the last function name and return value, sorry. Just updated the comment. Please update the code accordingly and it should work. Thanks.
