### ISSUE TITLE
concatenating column values

### ISSUE THREAD

**Issue by zxckoko** [freshbitsweb/laratables#79]
Hi,

How do I concatenate column values properly? I can seem to do it, but I can only invoke the customValues right after all other native/required values are there.

Say for example...

```php
public static function laratablesCustomFullname($user)
{
    return $user->firstname . ' ' . $lastname;
}
public static function laratablesAdditionalColumns()
{
        return ['firstname ', 'lastname'];
}
```
```javascript
columns: [
                    { name: 'object' , orderable: false},
]
```

![image](https://user-images.githubusercontent.com/10623125/72687791-842f7280-3b3c-11ea-80a5-dd86c02f5dfa.png)

`object` and `fullname` are one and the same in this example. Help please.

**Comment by gauravmak** [comment]
Either do `public static function laratablesCustomObject($user)` on the server side

or do `{ name: 'fullname' , orderable: false},` on the client side :)
