### ISSUE TITLE
Not Working With Ziggy packages

### ISSUE THREAD

**Issue by naingyy** [freshbitsweb/laratables#8]
Hi,

I'm using this package https://github.com/tightenco/ziggy for laravel routes in javascripts.

your package route not working with that package.
and has any configuration to use with "POST" method?.
 
Thanks!

**Comment by gauravmak** [comment]
Hi,

I haven't used Ziggy before. Can you provide more details?

Laratables doesn't have any routes itself. And the code is using Laravel's `request()` helper which captures GET as well as POST variables.

**Comment by yenyint** [comment]
Hi @gauravmak 

Thanks for your answers.

as Ziggy package we can use laravel route()  method in javascript file or within script tags ..
so I just use like this 
```
$('#users-table').DataTable({
    serverSide: true,
    ajax: route('users.datatables') ,
    columns: [
        { name: 'id' },
        { name: 'name' },
        { name: 'email' },
        { name: 'role.name' },
        { name: 'action', orderable: false, searchable: false }
    ],
    ...
});
```
its not woking.


Thanks!

**Comment by gauravmak** [comment]
Is the package working when you use Laravel `route()` helper?

If yes, `route('users.datatables')` isn't giving the same output as Laravel one.
If not, please provide exact error details.

**Comment by yenyint** [comment]
Hi @gauravmak,

yes working with laravel route() helper.my problem is solved
with ziggy package I just use``` route('users.datatables').url() ```method.

Thanks for your answer.

**Comment by gauravmak** [comment]
I guess this can be closed now.
