### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by otavio-araujo** [freshbitsweb/laratables#80]
Iam getting this error.

What could it be?

**Comment by gauravmak** [comment]
Please provide more details - Example code and stack trace.

**Comment by timoteo7** [comment]
@gauravmak

Like #84 #104

and in [Documentation](https://github.com/freshbitsweb/laratables#server-side):


``
return Laratables::recordsOf(User::class);
``

Return error ("Trying to access array offset on value of type null") in:

vendor/freshbitsweb/laratables/src/Laratables.php:88
``
$searchValue = request('search')['value'];
``


![image](https://user-images.githubusercontent.com/8633260/129293541-c721e5c6-a5d1-43bb-906b-b969d8742a31.png)

Laravel 8, PHP 8

**Comment by gauravmak** [comment]
> Return error in:
> 
> vendor/freshbitsweb/laratables/src/Laratables.php:88
> $searchValue = request('search')['value'];

What is the error exactly? Can you create a failing test?
