### ISSUE TITLE
How to implement an index column

### ISSUE THREAD

**Issue by zxckoko** [freshbitsweb/laratables#83]
Quick question: how do I implement something like this? https://datatables.net/examples/api/counter_columns.html

My implementation somehow gets overwritten... is there a way to create a dummy column that can be ignored by Laratables?

**Comment by gauravmak** [comment]
Yes, it is doable.

Please check the `Customize column` example on our [demo site](https://laratables.freshbits.in/).

Thanks.

**Comment by zxckoko** [comment]
Thanks, @gauravmak ! I am AFK atm, so I could not test it myself. Just want to clarify further... where did `request()->input('start')` come from?

**Comment by gauravmak** [comment]
When the user clicks on Page 2 (or more), datatables passes the `start` number which we can use to display the sr. numbers properly.

**Comment by zxckoko** [comment]
Oh. So, it's a `datatables`-specific parameter then... I see. Thank you very much.

**Comment by fadhil1106** [comment]
> Yes, it is doable.
> 
> Please check the `Customize column` example on our [demo site](https://laratables.freshbits.in/).
> 
> Thanks.

Where can I see the example?
the demo link is unreachable
