### ISSUE TITLE
How do I make the one to one polymorphic relationship searchable?

### ISSUE THREAD

**Issue by gxmp** [freshbitsweb/laratables#86]
Here's the client side
![image](https://user-images.githubusercontent.com/56036400/78220299-d5bc8c00-74f3-11ea-9511-aae26019e457.png)

This is my custom column 
![image](https://user-images.githubusercontent.com/56036400/78220882-ee797180-74f4-11ea-9471-322adf341446.png)

This is the searching for that column
![image](https://user-images.githubusercontent.com/56036400/78220609-6d21df00-74f4-11ea-903d-250b3b006b30.png)

It successfully went to the searching method but I can't fetch any record

**Comment by gauravmak** [comment]
Should it be `orWhereHasMorph` instead of `whereHasMorph`?

**Comment by gxmp** [comment]
> Should it be `orWhereHasMorph` instead of `whereHasMorph`?

This works, Thanks!
