### ISSUE TITLE
Is the ID column hard-coded?

### ISSUE THREAD

**Issue by rabbanirasha** [freshbitsweb/laratables#89]
There is no way I can change the SQL Statement possibly in this format "SELECT 'id', [col2],[col3].." when my database table has ID column (pkey) named anything other than ''id". For instance, If my ID column name is "pid", the recordsOf(User::class) method runs "SELECT 'id', 'pid',[col2]...." instead of "SELECT 'pid',[col2]...." and error "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'" occurs. So please do something so that I can either customize what specific columns I SELECT on or exclude particular columns. You can overload the method to accept more arguments like recordsOf(User::class,"pid, description, price") for example.

**Comment by gauravmak** [comment]
Hi,

`id` column is not hard-coded. You can set the [primary key](https://laravel.com/docs/7.x/eloquent#eloquent-model-conventions) name in the model.

```php
    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'pid';
```

**Comment by rabbanirasha** [comment]
This worked. Thank you so much for the quick and helpful reply. Laratables is like a godsend to us and heartfelt compliments to you guys who worked to build it.

**Comment by gauravmak** [comment]
Thanks
