### ISSUE TITLE
Limit is not a number

### ISSUE THREAD

**Issue by felipesp88** [freshbitsweb/laratables#9]
When I tried to use the package, it appears the message:

> Expected "limit" option to have type "integer" but found "string"

I think that it can be easily corerected if you change, in the Laratables class, the lines:

`->offset(request('start'))->limit(request('length'))`

to:

`->offset(intval(request('start')))->limit(intval(request('length')))`

The `offset` didn't appear in the message, but I think that it could be done to prevent the error.

**Comment by gauravmak** [comment]
Should be fixed with the new release, thanks.
