### ISSUE TITLE
One to One relationship Data returns N/A

### ISSUE THREAD

**Issue by matthaselip** [freshbitsweb/laratables#91]
Hi.  I have a table with multiple model relationships however they seem to only return N/A.  I am following your One To One Guide.

My jquery code

` <script type="text/javascript">
            window.onload = function () {
                $('#leads-table').DataTable({
                    "order": [[ 2, "desc" ]],
                    serverSide: true,
                    ajax: "{{ route('getLeads') }}",
                    columns: [
                        { name: 'status.lead_statuses_name', orderable: false },
                        { name: 'created_at' },
                        { name: 'created_at' },
                        { name: 'customers_id' },
                        { name: 'vehicles_id' },
                        { name: 'vehicles_id' },
                        { name: 'priority.lead_priorities_name' },
                        { name: 'action', orderable: false, searchable:false },
                    ],
                });
            }
        </script>`

Model

` /**
     * get status
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function status()
    {
        return $this->hasOne('App\LeadStatus','lead_statuses_id','lead_statuses_id');
    }

    /**
     * return priority
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function priority()
    {
        return $this->hasOne('App\leadPriority','lead_priorities_id','lead_priorities_id');
    }`

so im not too sure why both relationships are showing as returned data as N/A?

**Comment by gauravmak** [comment]
Please format the code correctly.

And if you [manually try](https://laravel.com/docs/8.x/eloquent-relationships#eager-loading) to fetch leads with status and priority, does it work?

**Comment by matthaselip** [comment]
Yes, manually fetching the lead by using 

`$lead = Lead::find(1)`

and then checking status and priority works against the relationship

`dd($lead->status->lead_statuses_name);`

and

`dd($lead->priority->lead_priorities_name);`

**Comment by matthaselip** [comment]
ok its fixed, thank you for your quick response 👍
