### ISSUE TITLE
buttons with javascript prevent default not working

### ISSUE THREAD

**Issue by deep80** [freshbitsweb/laratables#93]
i followed along as per the examples and documentation and added actions column with 2 buttons edit and delete (typical basic crud). in the delete button i need to add `preventdefault()` and submit a form to delete a data (soft delete) via jquery.

i was not able to grab the selector elements as the console was empty. E.g. `console.log($('.element'))` !! things aren't logging.

I am using laravel mix for the javascript part and also implemented datatable like this. worked flawlessly.

Please advise !!

**Comment by gauravmak** [comment]
This is a datatables related question. Please ask in [their forum](https://datatables.net/forums/). Laratables helps you with server-side code of fetching the data, nothing more. Thanks.

**Comment by deep80** [comment]
thanks for letting me know that. i figured it out. Actually i am new to jquery datatable !!!
