### ISSUE TITLE
Laratable Class accepting parameters

### ISSUE THREAD

**Issue by sentiasa** [freshbitsweb/laratables#94]
I've been using laratables for a while, great package!

I started using the separate class for Laratables approach and I started to really like it.
`return Laratables::recordsOf(User::class, UserLaratables::class);`

However, I wish there was a way to initialize `UserLaratables::class` in the Controller so that I can give it parameters. Something like:

```
$laratableClass = new UserLaratables($param1, $param2);
return Laratables::recordsOf(User::class, $laratableClass);
```

-----

The use-case would be, sometimes I have Advanced Search that get from:
```
public function getData() {
         $queries = request()->only( array_keys($this->queryFields) );
         $laratableClass = new UserLaratables($queries);
         return Laratables::recordsOf(User::class, $laratableClass);
}
```

So that in the UserLaratables class, we can run custom queries:

```
class UserLaratables
{
    private $queries;

   public function __construct($queries)
    {
        $this->queries = $queries;
    }

    public static function laratablesQueryConditions($query)
    {
        if (isset($this->queries['show-trashed']) && $this->queries['show-trashed'] == true) {
            $query = $query->withTrashed();
        }

        return $query;
    }
}
```
---

Is there a way to achieve that? Or would you accept a PR like that?

**Comment by gauravmak** [comment]
Hi,

Good to know that this package is useful to you.

Talking about your example, the good thing about Laravel is that you can access the request details anywhere using a helper function or dependency injection. Hence, there is no need to pass request details to a class manually. Correct?

**Comment by sentiasa** [comment]
The example I gave was a pretty primitive example. Let me show you my actual use-case.
```
class MyController {
     protected $advancedFilters = [
         'field_name' => "Readable Name"
     ];

     public function index() {
          return view('example')->with(['filtersFields' => $advancedFilters]);
     }

     public function getData() {
          $queries = request()->only( array_keys($this->advancedFilters) );

         // here I use the filtered request data to apply the advanced filters.
     }
}
```
----

The only way comes to my mind is advancedFilters live inside UserLaratables class as static properties so that I can access them both in Controller and LaratableClass.

Can you think of any other solution?

----

With a little tweak, what comes to my mind is maybe this. I am just suggesting a little feature that would help me. Your package, your preference :)
```
    return Laratables::recordsOf(User::class, UserLaratables::class, $extraParams);
```

**Comment by gauravmak** [comment]
Yeah, keeping a constant array or static property makes sense. I would try that if I were in your place.

**Comment by sentiasa** [comment]
Yeah, I moved the advancedFilters array to UserLaratables class, it works now and feels clean.

**Comment by ghost** [comment]
I think it's still a good idea to have a 3rd param with extra data that contains dynamic data that is only available in the controller. Any ideas on how to achieve that? @gauravmak

**Comment by gauravmak** [comment]
I guess you will need to use session data for the same.
