### ISSUE TITLE
No way to whitelist columns server-side

### ISSUE THREAD

**Issue by pavel-lexyr** [freshbitsweb/laratables#96]
A maliciously crafted query from the client can fetch any column in the server-side model, and in any related model as well. As of right now, there is no documented way to prevent this from happening and no strong recommendation to do this. This poses a risk to the security of user data.

**Comment by gauravmak** [comment]
Thanks for bringing this up Pavel.

Currently, there is no documentation of recommendation for the same. I am open to your ideas and PR for the same.

**Comment by gauravmak** [comment]
https://github.com/freshbitsweb/laratables/commit/1c52417b22412489ce4bc3e7f805d656481c340a
