### ISSUE TITLE
Add group by feature

### ISSUE THREAD

**Issue by janakaedirisinghe** [freshbitsweb/laratables#97]
```
public static function laratablesQueryConditions($query)
    {
        return $query->select(
            DB::raw('YEAR(created_at) as year,MONTHNAME(created_at) as month, SUM(delivery_charge) as total_delivery_charge, 
                           created_at'))
            ->groupByRaw('year(created_at),month(created_at)')
            ->orderByRaw('year(created_at),month(created_at)','desc');

    }
```
```

public static function laratablesSearchCreatedAt($query, $searchValue)
    {
        if (strpos($searchValue, ' - ')) {
            $dates = explode(' - ', $searchValue);   
            $query->whereBetween('created_at' ,[Carbon::parse($dates[0]), Carbon::parse($dates[1])]);     
        }
  }
```

when I filter by the date it shows all row count in the footer. But It shows 1 row only for the result of the filter. That is correct.  The problem is entries count wrong in the footer.

**Comment by gauravmak** [comment]
Is the issue about pagination or about footer count?

And can you recreate the issue with a simple example without the grouping?

**Comment by janakaedirisinghe** [comment]
Thanks for the reply!! Yeah, the issue about the footer row count. Assume if we filter 1000 records for the grouping and its output is 2 records after grouping. But the datatable footer shows "Showing 1 to 10 of 1000 entries".

**Comment by gauravmak** [comment]
Is the issue happening when you do not do the manual group by?

**Comment by janakaedirisinghe** [comment]
No.. The problem occurs when I group manually.

**Comment by gauravmak** [comment]
Thanks for checking and sharing this.

This means that Laratables needs to add the group by feature.

I would welcome a PR for that if you're open. Thanks.

**Comment by gauravmak** [comment]
Thanks for the suggestion @janakaedirisinghe but no plans for now - https://github.com/freshbitsweb/laratables/commit/bd9fd6fa31ef8255b265e5a56586591c63061307
