### ISSUE TITLE
does this support complex multiple row headers?

### ISSUE THREAD

**Issue by ChaerilM** [freshbitsweb/laratables#98]
the only thing stopping me from using Yajra in the past ~6 years that it does not support complex headers, specifically FixedHeader. does this support it?

thanks

**Comment by gauravmak** [comment]
Maybe you haven't read the Readme file yet. The client-side (datatables setup) is completely in your hands. And this package helps you to quickly set up the server-side. So yes, you can use Fixed Headers and other features of the Datatables.
